### ISSUE TITLE
Question About Dataset and Rendering Code

### ISSUE THREAD

**Issue by jk4011** [nv-tlabs/L4GM-official#1]
Thank you for your excellent work and for sharing your insights through your paper. 
I thoroughly enjoyed reading it and found it highly informative.

I have a few questions regarding the dataset used in your study. 
You mentioned utilizing 44K diverse objects from Objaverse. 
Could you kindly guide me on where I can find animatable objects within Objaverse?

Additionally, I was wondering if you would be willing to share the rendering code mentioned in your paper. 
If it's possible to provide it, I believe it would greatly enhance the utility of your research.

Thank you for reading this.

**Comment by jiawei-ren** [comment]
Thank you for your interest in L4GM! The rendering code is already in [blender_scripts/render_objaverse.py](https://github.com/nv-tlabs/L4GM-official/blob/main/blender_scripts/render_objaverse.py). 

To get all animations in Objaverse:
```python
def filter_animation():
    metadata_path = os.path.join(BASE_PATH, "metadata")
    animation_list = []
    for i in tqdm(range(160)):
        i_id = f"{i // 1000:03d}-{i % 1000:03d}"
        json_file = f"{i_id}.json.gz"
        local_path = os.path.join(metadata_path, json_file)
        if not os.path.exists(local_path):
            hf_url = f"https://huggingface.co/datasets/allenai/objaverse/resolve/main/metadata/{i_id}.json.gz"
            # wget the file and put it in local_path
            os.makedirs(os.path.dirname(local_path), exist_ok=True)
            urllib.request.urlretrieve(hf_url, local_path)
        with gzip.open(local_path, "rb") as f:
            data = json.load(f)
        
        # check animation count
        for t in data:
            for animation_idx in range(data[t]['animationCount']):
                animation_list.append(f"{i_id}/{t}/{animation_idx}")
    return animation_list
```

**Comment by jk4011** [comment]
Thank you. I'll try reproducing the data :D
